// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: broadcast_protobuf.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 发送消息
type BroadcastReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq     string `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`         // 序列号
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 消息内容
}

func (x *BroadcastReq) Reset() {
	*x = BroadcastReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastReq) ProtoMessage() {}

func (x *BroadcastReq) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastReq.ProtoReflect.Descriptor instead.
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return file_broadcast_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastReq) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *BroadcastReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BroadcastAppReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq     string `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`         // 序列号
	Aid     string `protobuf:"bytes,2,opt,name=aid,proto3" json:"aid,omitempty"`         // 应用ID
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // msg
}

func (x *BroadcastAppReq) Reset() {
	*x = BroadcastAppReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastAppReq) ProtoMessage() {}

func (x *BroadcastAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastAppReq.ProtoReflect.Descriptor instead.
func (*BroadcastAppReq) Descriptor() ([]byte, []int) {
	return file_broadcast_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastAppReq) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *BroadcastAppReq) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *BroadcastAppReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BroadcastFdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq     string `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`         // 序列号
	Aid     string `protobuf:"bytes,2,opt,name=aid,proto3" json:"aid,omitempty"`         // 应用ID
	Fd      string `protobuf:"bytes,3,opt,name=fd,proto3" json:"fd,omitempty"`           // 链接ID
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // msg
}

func (x *BroadcastFdReq) Reset() {
	*x = BroadcastFdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastFdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastFdReq) ProtoMessage() {}

func (x *BroadcastFdReq) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastFdReq.ProtoReflect.Descriptor instead.
func (*BroadcastFdReq) Descriptor() ([]byte, []int) {
	return file_broadcast_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastFdReq) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *BroadcastFdReq) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *BroadcastFdReq) GetFd() string {
	if x != nil {
		return x.Fd
	}
	return ""
}

func (x *BroadcastFdReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BroadcastUidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq     string `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`         // 序列号
	Aid     string `protobuf:"bytes,2,opt,name=aid,proto3" json:"aid,omitempty"`         // 应用ID
	Uid     string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`         // 用户ID
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // msg
}

func (x *BroadcastUidReq) Reset() {
	*x = BroadcastUidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_protobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastUidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastUidReq) ProtoMessage() {}

func (x *BroadcastUidReq) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_protobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastUidReq.ProtoReflect.Descriptor instead.
func (*BroadcastUidReq) Descriptor() ([]byte, []int) {
	return file_broadcast_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastUidReq) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *BroadcastUidReq) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *BroadcastUidReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BroadcastUidReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BroadcastGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq     string `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`         // 序列号
	Aid     string `protobuf:"bytes,2,opt,name=aid,proto3" json:"aid,omitempty"`         // 应用ID
	Gid     string `protobuf:"bytes,3,opt,name=gid,proto3" json:"gid,omitempty"`         // 组ID
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // msg
}

func (x *BroadcastGroupReq) Reset() {
	*x = BroadcastGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_protobuf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastGroupReq) ProtoMessage() {}

func (x *BroadcastGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_protobuf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastGroupReq.ProtoReflect.Descriptor instead.
func (*BroadcastGroupReq) Descriptor() ([]byte, []int) {
	return file_broadcast_protobuf_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastGroupReq) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *BroadcastGroupReq) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *BroadcastGroupReq) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *BroadcastGroupReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BroadcastRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Seq     string `protobuf:"bytes,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *BroadcastRsp) Reset() {
	*x = BroadcastRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_protobuf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRsp) ProtoMessage() {}

func (x *BroadcastRsp) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_protobuf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRsp.ProtoReflect.Descriptor instead.
func (*BroadcastRsp) Descriptor() ([]byte, []int) {
	return file_broadcast_protobuf_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastRsp) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BroadcastRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BroadcastRsp) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

var File_broadcast_protobuf_proto protoreflect.FileDescriptor

var file_broadcast_protobuf_proto_rawDesc = []byte{
	0x0a, 0x18, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x22, 0x3a, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x4f, 0x0a, 0x0f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x5e, 0x0a, 0x0e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x46, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x66, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x61, 0x0a, 0x0f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x55, 0x69,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x63, 0x0a, 0x11, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x67, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4e, 0x0a, 0x0c, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x71, 0x32, 0xb6, 0x02, 0x0a, 0x09, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x02, 0x46, 0x64, 0x12, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x46, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x3a, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x55, 0x69, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x03, 0x41, 0x70, 0x70, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x03, 0x41, 0x6c, 0x6c,
	0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70,
	0x22, 0x00, 0x42, 0x2c, 0x0a, 0x19, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42,
	0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_broadcast_protobuf_proto_rawDescOnce sync.Once
	file_broadcast_protobuf_proto_rawDescData = file_broadcast_protobuf_proto_rawDesc
)

func file_broadcast_protobuf_proto_rawDescGZIP() []byte {
	file_broadcast_protobuf_proto_rawDescOnce.Do(func() {
		file_broadcast_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_broadcast_protobuf_proto_rawDescData)
	})
	return file_broadcast_protobuf_proto_rawDescData
}

var file_broadcast_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_broadcast_protobuf_proto_goTypes = []interface{}{
	(*BroadcastReq)(nil),      // 0: protobuf.BroadcastReq
	(*BroadcastAppReq)(nil),   // 1: protobuf.BroadcastAppReq
	(*BroadcastFdReq)(nil),    // 2: protobuf.BroadcastFdReq
	(*BroadcastUidReq)(nil),   // 3: protobuf.BroadcastUidReq
	(*BroadcastGroupReq)(nil), // 4: protobuf.BroadcastGroupReq
	(*BroadcastRsp)(nil),      // 5: protobuf.BroadcastRsp
}
var file_broadcast_protobuf_proto_depIdxs = []int32{
	2, // 0: protobuf.Broadcast.Fd:input_type -> protobuf.BroadcastFdReq
	3, // 1: protobuf.Broadcast.Uid:input_type -> protobuf.BroadcastUidReq
	4, // 2: protobuf.Broadcast.Group:input_type -> protobuf.BroadcastGroupReq
	1, // 3: protobuf.Broadcast.App:input_type -> protobuf.BroadcastAppReq
	0, // 4: protobuf.Broadcast.All:input_type -> protobuf.BroadcastReq
	5, // 5: protobuf.Broadcast.Fd:output_type -> protobuf.BroadcastRsp
	5, // 6: protobuf.Broadcast.Uid:output_type -> protobuf.BroadcastRsp
	5, // 7: protobuf.Broadcast.Group:output_type -> protobuf.BroadcastRsp
	5, // 8: protobuf.Broadcast.App:output_type -> protobuf.BroadcastRsp
	5, // 9: protobuf.Broadcast.All:output_type -> protobuf.BroadcastRsp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_broadcast_protobuf_proto_init() }
func file_broadcast_protobuf_proto_init() {
	if File_broadcast_protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_broadcast_protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastAppReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastFdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_protobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastUidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_protobuf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_protobuf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_broadcast_protobuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broadcast_protobuf_proto_goTypes,
		DependencyIndexes: file_broadcast_protobuf_proto_depIdxs,
		MessageInfos:      file_broadcast_protobuf_proto_msgTypes,
	}.Build()
	File_broadcast_protobuf_proto = out.File
	file_broadcast_protobuf_proto_rawDesc = nil
	file_broadcast_protobuf_proto_goTypes = nil
	file_broadcast_protobuf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BroadcastClient is the client API for Broadcast service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BroadcastClient interface {
	// 向fd发送消息
	Fd(ctx context.Context, in *BroadcastFdReq, opts ...grpc.CallOption) (*BroadcastRsp, error)
	// 向用户发送消息
	Uid(ctx context.Context, in *BroadcastUidReq, opts ...grpc.CallOption) (*BroadcastRsp, error)
	// 向组发送消息
	Group(ctx context.Context, in *BroadcastGroupReq, opts ...grpc.CallOption) (*BroadcastRsp, error)
	// 向app发送消息
	App(ctx context.Context, in *BroadcastAppReq, opts ...grpc.CallOption) (*BroadcastRsp, error)
	// 向所有连接发送消息
	All(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*BroadcastRsp, error)
}

type broadcastClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadcastClient(cc grpc.ClientConnInterface) BroadcastClient {
	return &broadcastClient{cc}
}

func (c *broadcastClient) Fd(ctx context.Context, in *BroadcastFdReq, opts ...grpc.CallOption) (*BroadcastRsp, error) {
	out := new(BroadcastRsp)
	err := c.cc.Invoke(ctx, "/protobuf.Broadcast/Fd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *broadcastClient) Uid(ctx context.Context, in *BroadcastUidReq, opts ...grpc.CallOption) (*BroadcastRsp, error) {
	out := new(BroadcastRsp)
	err := c.cc.Invoke(ctx, "/protobuf.Broadcast/Uid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *broadcastClient) Group(ctx context.Context, in *BroadcastGroupReq, opts ...grpc.CallOption) (*BroadcastRsp, error) {
	out := new(BroadcastRsp)
	err := c.cc.Invoke(ctx, "/protobuf.Broadcast/Group", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *broadcastClient) App(ctx context.Context, in *BroadcastAppReq, opts ...grpc.CallOption) (*BroadcastRsp, error) {
	out := new(BroadcastRsp)
	err := c.cc.Invoke(ctx, "/protobuf.Broadcast/App", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *broadcastClient) All(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*BroadcastRsp, error) {
	out := new(BroadcastRsp)
	err := c.cc.Invoke(ctx, "/protobuf.Broadcast/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BroadcastServer is the server API for Broadcast service.
type BroadcastServer interface {
	// 向fd发送消息
	Fd(context.Context, *BroadcastFdReq) (*BroadcastRsp, error)
	// 向用户发送消息
	Uid(context.Context, *BroadcastUidReq) (*BroadcastRsp, error)
	// 向组发送消息
	Group(context.Context, *BroadcastGroupReq) (*BroadcastRsp, error)
	// 向app发送消息
	App(context.Context, *BroadcastAppReq) (*BroadcastRsp, error)
	// 向所有连接发送消息
	All(context.Context, *BroadcastReq) (*BroadcastRsp, error)
}

// UnimplementedBroadcastServer can be embedded to have forward compatible implementations.
type UnimplementedBroadcastServer struct {
}

func (*UnimplementedBroadcastServer) Fd(context.Context, *BroadcastFdReq) (*BroadcastRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fd not implemented")
}
func (*UnimplementedBroadcastServer) Uid(context.Context, *BroadcastUidReq) (*BroadcastRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Uid not implemented")
}
func (*UnimplementedBroadcastServer) Group(context.Context, *BroadcastGroupReq) (*BroadcastRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Group not implemented")
}
func (*UnimplementedBroadcastServer) App(context.Context, *BroadcastAppReq) (*BroadcastRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method App not implemented")
}
func (*UnimplementedBroadcastServer) All(context.Context, *BroadcastReq) (*BroadcastRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}

func RegisterBroadcastServer(s *grpc.Server, srv BroadcastServer) {
	s.RegisterService(&_Broadcast_serviceDesc, srv)
}

func _Broadcast_Fd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastFdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServer).Fd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Broadcast/Fd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServer).Fd(ctx, req.(*BroadcastFdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broadcast_Uid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastUidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServer).Uid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Broadcast/Uid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServer).Uid(ctx, req.(*BroadcastUidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broadcast_Group_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServer).Group(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Broadcast/Group",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServer).Group(ctx, req.(*BroadcastGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broadcast_App_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServer).App(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Broadcast/App",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServer).App(ctx, req.(*BroadcastAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broadcast_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Broadcast/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServer).All(ctx, req.(*BroadcastReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Broadcast_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Broadcast",
	HandlerType: (*BroadcastServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fd",
			Handler:    _Broadcast_Fd_Handler,
		},
		{
			MethodName: "Uid",
			Handler:    _Broadcast_Uid_Handler,
		},
		{
			MethodName: "Group",
			Handler:    _Broadcast_Group_Handler,
		},
		{
			MethodName: "App",
			Handler:    _Broadcast_App_Handler,
		},
		{
			MethodName: "All",
			Handler:    _Broadcast_All_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broadcast_protobuf.proto",
}
